config/routes.rb
Distibutor::Application.routes.draw do
  mount Tail::Engine, at: '/tail'

  get 'main/index'
  get 'main/main'

  resources :logs, only: [:index, :destroy] do
    collection do
      get 'clear_log' => 'logs#clear_log'
    end
  end

  resources :settings, only: [:index, :show, :edit, :update] do
    collection do
      post 'import_preview' => 'settings#import_standard_prices_preview'
      get 'import_standard_prices' => 'settings#import_standard_prices'

      post 'all' => 'settings#all_sites_preview'
      get 'all' => 'settings#all_sites_import'

      post 'import_shops_preview' => 'settings#import_user_sites_preview'
      get 'import_shops' => 'settings#import_user_sites'

      get 'export_shops_preview' => 'settings#export_shops_preview'
      get 'export_shops' => 'settings#export_shops'
    end
  end

  resources :items, only: [:index, :show] do
    collection do
      get 'refine_items' => 'items#refine_items'
    end
  end

  resources :urls, only: [:index] do
    member do
      get 'upd' => 'urls#update_single_price'
    end
    collection do
      get 'update_violators' => 'urls#update_violators'
      get 'find_urls' => 'urls#find_urls'
    end
  end

  resources :sites, only: [:index, :show, :edit, :update, :new] do
    collection do
      get 'stop_list' => 'sites#stop_list'
      get 'search' => 'sites#search'
    end

    member do
      get 'logs'
      get 'logs_submit'
      get 'violators'
      get 'row'
      get 'update_prices' => 'sites#update_prices'
    end

  end

  get '/dj' => DelayedJobWeb, :anchor => false

  resources :groups, only: [:show]

  devise_for :users

  root 'main#index'

end

app/models/settings.rb
class Settings < ActiveRecord::Base
belongs_to :group
end

app/controllers/settings_controller.rb
class SettingsController < ApplicationController
  before_filter :authenticate_user!
  before_action :set_setting, only: [:show, :edit, :update, :destroy]

  def export_shops()
    sites = Site.all
    create_sites_file(sites)
    #users = User.all
    #create_user_folders(users)
    #
    #create_zip_folder
    redirect_to sites_path
  end

  def export_shops_preview
    @sites = ["_sites", Site.all]
    @folders = []

    @users = User.all.order("username")
    @users.each do |user|
      user_folders = []
      user.groups.each do |group|
        user_folders << [group.name, group.items.order("name"), group.sites.order("name"), "standard.xlsx"]
      end
      @folders << [user.username, user_folders]
    end

  end

  def import_user_sites_preview
    begin
      @shops = params[:shops]
      if @shops.nil?
        redirect_to settings_path, alert: 'Выберите файл'
        return
      end

      @sites = []
      spreadsheet = Roo::Excelx.new(@shops.path, nil, :ignore)
      spreadsheet.sheets.each do |sheet|
        spreadsheet.default_sheet = sheet
        group = Group.where(name: sheet).first
        next if group.nil?

        (2..spreadsheet.last_row).each do |i|
          @sites << [sheet, spreadsheet.row(i)[0]]
        end
      end

      File.open('./tmp/' + current_user.username + '_shops' + '.xlsx', 'w') do |tempfile|
        tempfile.write(@shops.tempfile.set_encoding('utf-8').read)
      end
    rescue
      redirect_to settings_path, alert: 'Произошла ошибка импорта.'
    end

  end

  #список магазинов по группам

  def import_user_sites(filename='./tmp/' + current_user.username + '_shops'+'.xlsx')
    begin
      current_user.shops_file_import(filename)
      redirect_to settings_path, success: 'Список могазинов обновлен.'

    rescue
      redirect_to settings_path, alert: 'Произошла ошибка импорта.'
    end
  end

  #список магазинов по группам

  def import_standard_prices_preview
    begin
      @file = params[:file]
      if @file.nil?
        redirect_to settings_path, alert: 'Выберите файл'
        return
      end

      @items = []
      spreadsheet = Roo::Excelx.new(@file.path, nil, :ignore)
      spreadsheet.sheets.each do |sheet|
        spreadsheet.default_sheet = sheet
        @header = spreadsheet.row(1)

        (2..spreadsheet.last_row).each do |i|
          row = Hash[[@header, spreadsheet.row(i)].transpose]
          if !row['item_id'].nil?
            @items << [sheet, row['item_id'], row['price']]
          else
            next
          end
        end
      end

      File.open('./tmp/' + current_user.username + '.xlsx', 'w') do |tempfile|
        tempfile.write(@file.tempfile.set_encoding('utf-8').read)
      end
    rescue
      redirect_to settings_path, alert: 'Произошла ошибка импорта.'
    end


  end

  #стандартные цены

  def import_standard_prices(filename='./tmp/' + current_user.username + '.xlsx')
    begin
      current_user.standard_site_import(filename)
      redirect_to settings_path, success: 'Цены импортированы'
    rescue
      redirect_to settings_path, alert: 'Произошла ошибка импорта.'
    end
  end

  #стандартные цены

  def all_sites_import(filename='./tmp/sites_' + current_user.username + '.xlsx')
    begin
      current_user.all_sites_import(filename)
      redirect_to sites_path, success: 'Информация о сайтах импортирована'
    rescue
      redirect_to settings_path, alert: 'Произошла ошибка импорта.'
    end
  end

  #параметры сайтов

  def all_sites_preview
    begin
      @file = params[:sites]
      if @file.nil?
        redirect_to settings_path, alert: 'Выберите файл'
        return
      end
      #begin
      spreadsheet = Roo::Excelx.new(@file.path, nil, :ignore)
      @sites = []

      @header = spreadsheet.row(1)
      (2..spreadsheet.last_row).each do |i|
        @sites << spreadsheet.row(i)
      end
      File.open('./tmp/sites_' + current_user.username + '.xlsx', 'w') do |tempfile|
        tempfile.write(@file.tempfile.set_encoding('utf-8').read)
      end
    rescue
      redirect_to settings_path, alert: 'Произошла ошибка импорта.'
    end
  end

#параметры сайтов

  def index
    @sites_exist = !Site.all.empty?
    @user_standard_site_exists = !Site.joins(:groups).where(standard: true, groups: {'user' => current_user}).uniq.empty?
    if current_user.admin?
      @groups = Group.all
    else
      @groups = current_user.groups
    end
  end

  def show
  end

  def new
    @setting = Settings.new
  end

  def edit
  end

  def create
    @setting = Settings.new(setting_params)

    respond_to do |format|
      if @setting.save
        format.html { redirect_to @setting, notice: 'Settings was successfully created.' }
        format.json { render action: 'show', status: :created, location: @setting }
      else
        format.html { render action: 'new' }
        format.json { render json: @setting.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @setting.update(setting_params)
        format.html { redirect_to @setting, notice: 'Настройки успешно обновлены.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @setting.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @setting.destroy
    respond_to do |format|
      format.html { redirect_to settings_index_url }
      format.json { head :no_content }
    end
  end

  private
  def set_setting
    if current_user.admin?
      @setting = Settings.find(params[:id])
    else
      @setting = Settings.joins(:group => :user).where(groups: {user_id: current_user.id}, id: params[:id]).readonly(false).first
    end
    redirect_to root_path, alert: 'Некорректный адрес.' if @setting.nil?
  end

  def setting_params
    params.require(:settings).permit(:ban_time, :last_updated, :allowed_error, :update_time, :rate)
  end

  def create_sites_file (sites)
    permissions = 0755
    p Dir.pwd
    mkdir("export", permissions)
    Dir.chdir("export") do
      p Dir.pwd

      mkdir("_sites", permissions)
      Dir.chdir("_sites") do
        p Dir.pwd

        Axlsx::Package.new do |p|
          p.workbook.add_worksheet(:name => "all_sites") do |sheet|
            sheet.add_row Site.first.attributes.keys
            sites.each do |site|
              row = site.attributes.values
              sheet.add_row row
            end
          end
          p.serialize("all_sites.xlsx")
        end

        standard_site = sites.where(standard: true).first
        Axlsx::Package.new do |p|
          standard_site.groups.order("name").each do |group|
            p.workbook.add_worksheet(name: group.name) do |sheet|
              sheet.add_row ["group_id", "item", "price"]
              group_items = standard_site.items.find_all { |item| item.get_group_name == group.name }
              group_items = group_items.sort_by { |item| item.name }
              group_items.each { |item| sheet.add_row [group.name, item.name, get_price(standard_site, item)] }
            end
          end
          p.serialize("standard.xlsx")
        end
      end
    end
  end

  def mkdir(dirname, permissions=0755)
    begin
      Dir.mkdir(dirname, permissions)
    rescue => e
      p e.inspect
    end
  end


  def create_user_folders(users)
    Dir.chdir("export") do
      users.each do |user|
        mkdir(user.username)
        Dir.chdir(user.username) do
          user.groups.each do |group|
            mkdir(group.name)
            Dir.chdir(group.name) do
              #items.xlsx
              Axlsx::Package.new do |p|
                p.workbook.add_worksheet(:name => "items") do |sheet|
                  sheet.add_row ["name"]
                  group.items.order("name").each { |item| sheet.add_row [item.name] }
                end
                p.serialize("items.xlsx")
              end

              #sites.xlsx
              Axlsx::Package.new do |p|
                p.workbook.add_worksheet(:name => "sites") do |sheet|
                  sheet.add_row ["name"]
                  group.sites.order("name").each { |site| sheet.add_row [site.name] }
                end
                p.serialize("sites.xlsx")
              end

            end
          end
        end
      end
    end
  end

  def create_zip_folder
    directory = './export/'
    zipfile_name = './export_file.zip'

    Zip::ZipFile.open(zipfile_name, Zip::ZipFile::CREATE) do |zipfile|
      Dir[File.join(directory, '**', '**')].each do |file|
        zipfile.add(file.sub(directory, ''), file)
      end
    end

  end

  def unzip_file (file, destination)
    Zip::ZipFile.open(file) { |zip_file|
      zip_file.each { |f|
        f_path=File.join(destination, f.name)
        FileUtils.mkdir_p(File.dirname(f_path))
        zip_file.extract(f, f_path) unless File.exist?(f_path)
      }
    }
  end


end

app/helpers/settings_helper.rb
module SettingsHelper
end

app/views/settings/_form.html.erb
<%= form_for @setting, :html => {:class => 'form-horizontal'} do |f| %>
    <div class="control-group">
      <%= f.label :ban_time, :class => 'control-label' %>
      <div class="controls">
        <%= f.text_field :ban_time, :class => 'text_field' %>
      </div>
    </div>
    <div class="control-group">
      <%= f.label :allowed_error, :class => 'control-label' %>
      <div class="controls">
        <%= f.text_field :allowed_error, :class => 'text_field' %>
      </div>
    </div>
    <div class="control-group">
      <%= f.label :rate, :class => 'control-label' %>
      <div class="controls">
        <%= f.text_field :rate, :class => 'text_field' %>
      </div>
    </div>

    <div class="form-actions">
      <%= f.submit 'Сохранить настройки', :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t('helpers.links.cancel')),
                  settings_path, :class => 'btn' %>
    </div>
<% end %>

app/views/settings/all_sites_preview.html.erb
<%- model_class = Site -%>
<div class="page-header">
  <h2><%= current_user.username %></h2>
</div>

<table class="table table-striped" id="preview">
  <thead>
  <% (0..@header.size).each do |i| %>
      <th><%= @header[i] %></th>
  <% end %>
  </thead>
  <tbody>
  <% @sites.each do |site| %>
      <tr>
        <% (0..site.size).each do |i| %>
            <td><%= site[i] %></td>
        <% end %>
      </tr>
  <% end %>
  </tbody>
</table>

<%= link_to 'Импорт', all_settings_path, :class => 'btn btn-primary', id: 'import' %>
<%= link_to 'Назад', settings_path, :class => 'btn', id: 'cancel' %>

app/views/settings/edit.html.erb
<%- model_class = Settings -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/settings/export_shops_preview.html.erb
<div class="page-header">
  <h2><%= current_user.username %></h2>
</div>

<% if current_user.admin? %>
    <div class="row">
      <div class="span1 offset1">
        /<%= @sites[0] %>
      </div>
    </div>
    <div class="row">
      <div class="span12 offset2">
        <table id="preview">
          <thead>
          <strong>/all_sites.xlsx</strong>
          <% Site.first.attributes.keys[1..3].each do |key| %>
              <th><%= key %></th>
          <% end %>
          </thead>
          <tbody>
          <% @sites[1].each do |site| %>
              <tr>
                <% site.attributes.values[1..3].each do |value| %>
                    <td><%= value %></td>
                <% end %>
              </tr>
          <% end %>
          </tbody>
        </table>
      </div>
    </div>


    <% @folders.each do |user_folder| %>
        <div class="row">
          <div class="span1 offset1">
            /<%= user_folder[0] %>
          </div>
        </div>
        <% user_folder[1].each do |folder| %>
            <div class="row">
              <div class="span1 offset2">
                /<%= folder[0] %>
              </div>
            </div>
            <div class="row">
              <div class="span2 offset3">
                <table>
                  <thead>
                  <th>/items.xlsx</th>
                  </thead>
                  <tbody>
                  <% folder[1].each do |item| %>
                      <tr>
                        <td>
                          <%= item.name %>
                        </td>
                      </tr>
                  <% end %>
                  </tbody>

                </table>
              </div>
              <div class="span2 offset1">
                <table>
                  <thead>
                  <th>/sites.xlsx</th>
                  </thead>
                  <tbody>
                  <% folder[2].each do |site| %>
                      <tr>
                        <td>
                          <%= site.name %>
                        </td>
                      </tr>
                  <% end %>
                  </tbody>

                </table>
              </div>
              <div class="span1">
                <strong>/<%= folder[3] %></strong>
              </div>
            </div>

        <% end %>
    <% end %>

    <%= link_to 'Экспорт', export_shops_settings_path, :class => 'btn btn-primary' %>

<% end %>

app/views/settings/import_standard_prices_preview.html.erb
<%- model_class = Site -%>
<div class="page-header">
  <h2><%= current_user.username %></h2>
</div>

<table class="table table-striped" id="preview">
  <thead>
  <th>Группа</th>
  <th>Название</th>
  <th>Цена</th>
  </thead>
  <tbody>
  <% @items.each do |item| %>
      <tr>
        <td><%= item[0] %></td>
        <td><%= item[1] %></td>
        <td><%= spaces(item[2]) %></td>
      </tr>
  <% end %>
  </tbody>
</table>

<%= link_to 'Импорт', import_standard_prices_settings_path, :class => 'btn btn-primary', id: 'import' %>
<%= link_to 'Назад', settings_path, :class => 'btn' %>

app/views/settings/import_user_sites_preview.html.erb
<%- model_class = Site -%>
<div class="page-header">
  <h2><%= current_user.username %></h2>
</div>

<table class="table table-striped" id="preview">
  <thead>
  <th>Группа</th>
  <th>Сайт</th>
  </thead>
  <tbody>
  <% @sites.each do |site| %>
      <tr>
        <td><%= site[0] %></td>
        <td><%= site[1] %></td>
      </tr>
  <% end %>
  </tbody>
</table>

<%= link_to 'Импорт', import_shops_settings_path, :class => 'btn btn-primary', id: 'import' %>
<%= link_to 'Назад', settings_path, :class => 'btn' %>

app/views/settings/index.html.erb
<%- model_class = Settings -%>
<div class="page-header">
  <h2><%= t '.title', :default => model_class.model_name.human.pluralize.titleize %></h2>
</div>

<% @groups.each do |group| %>
    <table class="table table-striped">
      <thead>
      <tr>
        <th>Группа</th>
        <th><%= model_class.human_attribute_name(:allowed_error) %></th>
        <th><%= model_class.human_attribute_name(:rate) %></th>
        <th></th>
      </tr>
      </thead>
      <tbody>
      <tr>
        <td class="span3"><%= group.name %></td>
        <td><%= group.settings.allowed_error %></td>
        <td><%= group.settings.rate %></td>
        <td><%= link_to 'Изменить', edit_setting_path(group.settings), :class => 'btn btn-mini' %></td>
      </tr>

      </tbody>
    </table>
<% end %>
<br>
<br>
<br>
<br>
<br>

<% if current_user.admin? %>
    <%= link_to 'Экспорт', export_shops_preview_settings_path, class: 'btn btn-primary', id: 'export' %>
    <br/>
    <%= form_tag all_settings_path, multipart: true do %>
        <%= file_field_tag 'sites' %>
        <%= submit_tag 'Импорт настроек сайтов', class: 'btn btn-primary', id:'all_sites_button' %>
    <% end %>
<% end %>

<%= form_tag import_preview_settings_path, multipart: true do %>
    <%= file_field_tag 'file' %>
    <%= submit_tag 'Импорт стандартных цен', class: 'btn btn-primary', disabled: !@sites_exist, id: 'standard_button'%>
<% end %>



<%= form_tag import_shops_preview_settings_path, multipart: true do %>
    <%= file_field_tag 'shops' %>
    <%= submit_tag 'Импорт списка магазинов для групп товаров', class: 'btn btn-primary', disabled: !@sites_exist || !@user_standard_site_exists, id: 'shops_button'  %>
<% end %>

app/views/settings/new.html.erb
<%- model_class = Settings -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/settings/show.html.erb
<%- model_class = Settings -%>
<div class="page-header">
  <h1>Настройки</h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:ban_time) %>:</strong></dt>
  <dd><%= @setting.ban_time %></dd>
  <dt><strong><%= model_class.human_attribute_name(:last_updated) %>:</strong></dt>
  <dd><%= @setting.last_updated %></dd>
  <dt><strong><%= model_class.human_attribute_name(:allowed_error) %>:</strong></dt>
  <dd><%= @setting.allowed_error %></dd>
  <dt><strong><%= model_class.human_attribute_name(:rate) %>:</strong></dt>
  <dd><%= @setting.rate %></dd>
  <dt><strong><%= model_class.human_attribute_name(:update_time) %>:</strong></dt>
  <dd><%= @setting.group.name %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t('helpers.links.back')),
              settings_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t('helpers.links.edit')),
              edit_setting_path(@setting.id), :class => 'btn' %>

</div>