config/routes.rb
Distibutor::Application.routes.draw do
  mount Tail::Engine, at: '/tail'

  get 'main/index'
  get 'main/main'

  resources :logs, only: [:index, :destroy] do
    collection do
      get 'clear_log' => 'logs#clear_log'
    end
  end

  resources :settings, only: [:index, :show, :edit, :update] do
    collection do
      post 'import_preview' => 'settings#import_standard_prices_preview'
      get 'import_standard_prices' => 'settings#import_standard_prices'

      post 'all' => 'settings#all_sites_preview'
      get 'all' => 'settings#all_sites_import'

      post 'import_shops_preview' => 'settings#import_user_sites_preview'
      get 'import_shops' => 'settings#import_user_sites'

      get 'export_shops_preview' => 'settings#export_shops_preview'
      get 'export_shops' => 'settings#export_shops'
    end
  end

  resources :items, only: [:index, :show] do
    collection do
      get 'refine_items' => 'items#refine_items'
    end
  end

  resources :urls, only: [:index] do
    member do
      get 'upd' => 'urls#update_single_price'
    end
    collection do
      get 'update_violators' => 'urls#update_violators'
      get 'find_urls' => 'urls#find_urls'
    end
  end

  resources :sites, only: [:index, :show, :edit, :update, :new] do
    collection do
      get 'stop_list' => 'sites#stop_list'
      get 'search' => 'sites#search'
    end

    member do
      get 'logs'
      get 'logs_submit'
      get 'violators'
      get 'row'
      get 'update_prices' => 'sites#update_prices'
    end

  end

  get '/dj' => DelayedJobWeb, :anchor => false

  resources :groups, only: [:show]

  devise_for :users

  root 'main#index'

end

app/models/item.rb
class Item < ActiveRecord::Base
  include PgSearch

  has_many :urls, dependent: :destroy
  has_many :sites, through: :urls
  belongs_to :group

  pg_search_scope :item_search, against: [:name],
                  :associated_against => {
                      :sites => [:name],
                      :group => :name
                  }


  def get_group_name
    Rails.cache.fetch([self, 'group_name']) { self.group.name }
  end
  def get_name
    Rails.cache.fetch([self, 'name']) { self.name }
  end

  def get_urls
    Rails.cache.fetch([self, 'urls']) { self.urls }
  end

  def get_standard_price
    #Rails.cache.fetch([self, 'standard_price']) do
    #rer
    if self.standard_price.nil?
      url = (self.get_urls & self.group.get_standard_site.urls).first
      self.standard_price = url.nil? ? nil : url.price
      self.save
    end
    self.standard_price
  end

  def get_standard_url
    Rails.cache.fetch([self, 'standard_url']) do
      #urls1 = self.get_urls
      #urls2 = self.group.get_standard_site.get_urls

      (self.urls & self.group.get_standard_site.urls).first
    end
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_filter :authenticate_user!
  before_action :set_item, only: [:show, :edit, :update, :destroy]

  # GET /items
  # GET /items.json
  def index
    if current_user.admin?
      @items = Item.all.order(:id)
    else
      @items = Item.joins(:group => :user).where(groups: {user_id: current_user.id}).order(:id)
    end
  end

  # GET /items/1
  # GET /items/1.json
  def show
  end

  # GET /items/new
  def new
    @item = Item.new
  end

  # GET /items/1/edit
  def edit
  end

  # POST /items
  # POST /items.json
  def create
    @item = Item.new(item_params)

    respond_to do |format|
      if @item.save
        format.html { redirect_to @item, notice: 'Item was successfully created.' }
        format.json { render action: 'show', status: :created, location: @item }
      else
        format.html { render action: 'new' }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /items/1
  # PATCH/PUT /items/1.json
  def update
    respond_to do |format|
      # debugger
      if @item.update(item_params)
        format.html { redirect_to @item, notice: 'Item was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /items/1
  # DELETE /items/1.json
  def destroy
    @item.destroy
    respond_to do |format|
      format.html { redirect_to items_url }
      format.json { head :no_content }
    end
  end
	
	def refine_items
		items = Item.joins(:group => :user).where(groups: {user_id: current_user.id})
		items.each do |item|
			name = item.name.gsub('Е', 'E').gsub('Н', 'H').gsub('О', 'O').gsub('Р', 'P').gsub('А', 'A').gsub('В', 'B').gsub('С', 'C').gsub('М', 'M').gsub('Т', 'T').gsub('К', 'K').gsub('Х', 'X').gsub('/', ' ').gsub('\\', ' ')
			item.name = name
			item.save
		end
		redirect_to items_path
	end
  private
  # Use callbacks to share common setup or constraints between actions.
  def set_item
    if current_user.admin?
      @item = Item.find(params[:id])
    else
      @item = Item.joins(:group => :user).where(groups: {user_id: current_user.id}, id: params[:id]).first
    end
    redirect_to root_path, alert: 'Некорректный адрес.' if @item.nil?
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def item_params
    params.require(:item).permit!#(:name, :group_id, urls_attributes: [:url, :id, :_destroy, :sites])
  end


end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/_form.html.erb
<%= form_for @item, :html => {:class => 'form-horizontal'} do |f| %>
    <div class="control-group">
      <%= f.label :name, :class => 'control-label' %>
      <div class="controls">
        <%= f.text_field :name, :class => 'text_field' %>
      </div>
    </div>
    <div class="control-group">
      <%= f.label :group_id, :class => 'control-label' %>
      <div class="controls">
        <%= f.text_field :group_id, :class => 'text_field' %>
      </div>
    </div>

    <div class="form-actions">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t('helpers.links.cancel')),
                  items_path, :class => 'btn' %>
    </div>
<% end %>

app/views/items/_url_fields.html.erb
<fieldset>
<%= f.label :url, 'Url' %>
<%= f.text_field :url %>
<%= f.hidden_field :_destroy %>
<%= link_to 'remove', '#', class: 'remove_fields' %>
</fieldset>

app/views/items/index.html.erb
<%- model_class = Item -%>
<div class="page-header">
  <h3>Позиции</h3>
</div>

<%= link_to 'Удалить ошибки в названиях', refine_items_items_path, :class => 'btn btn-primary' %>


<table class="table table-striped">
  <thead>
  <tr>
    <th><%= model_class.human_attribute_name(:id) %></th>
    <th><%= model_class.human_attribute_name(:name) %></th>
    <th><%= model_class.human_attribute_name(:group_id) %></th>
    <th><%= model_class.human_attribute_name(:created_at) %></th>
  </tr>
  </thead>
  <tbody>
  <% @items.each do |item| %>
      <tr>
        <td><%= link_to item.id, item_path(item) %></td>
        <td><%= item.name %></td>
        <td><%= item.group_id %></td>
        <td><%= item.created_at.to_formatted_s(:short) %></td>
      </tr>
  <% end %>
  </tbody>
</table>

app/views/items/new.html.erb
<%- model_class = Item -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/items/show.html.erb
<%- model_class = Item -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @item.name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:group_id) %>:</strong></dt>
  <dd><%= @item.group_id %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t('helpers.links.back')),
              items_path, :class => 'btn'  %>
  <%= link_to t('.destroy', :default => t('helpers.links.destroy')),
              item_path(@item),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t('helpers.links.confirm', :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>