config/routes.rb
Distibutor::Application.routes.draw do
  mount Tail::Engine, at: '/tail'

  get 'main/index'
  get 'main/main'

  resources :logs, only: [:index, :destroy] do
    collection do
      get 'clear_log' => 'logs#clear_log'
    end
  end

  resources :settings, only: [:index, :show, :edit, :update] do
    collection do
      post 'import_preview' => 'settings#import_standard_prices_preview'
      get 'import_standard_prices' => 'settings#import_standard_prices'

      post 'all' => 'settings#all_sites_preview'
      get 'all' => 'settings#all_sites_import'

      post 'import_shops_preview' => 'settings#import_user_sites_preview'
      get 'import_shops' => 'settings#import_user_sites'

      get 'export_shops_preview' => 'settings#export_shops_preview'
      get 'export_shops' => 'settings#export_shops'
    end
  end

  resources :items, only: [:index, :show] do
    collection do
      get 'refine_items' => 'items#refine_items'
    end
  end

  resources :urls, only: [:index] do
    member do
      get 'upd' => 'urls#update_single_price'
    end
    collection do
      get 'update_violators' => 'urls#update_violators'
      get 'find_urls' => 'urls#find_urls'
    end
  end

  resources :sites, only: [:index, :show, :edit, :update, :new] do
    collection do
      get 'stop_list' => 'sites#stop_list'
      get 'search' => 'sites#search'
    end

    member do
      get 'logs'
      get 'logs_submit'
      get 'violators'
      get 'row'
      get 'update_prices' => 'sites#update_prices'
    end

  end

  get '/dj' => DelayedJobWeb, :anchor => false

  resources :groups, only: [:show]

  devise_for :users

  root 'main#index'

end

app/models/site.rb
#encoding: UTF-8
require 'rubygems'
require 'open-uri'
require 'rubyXL'
require 'axlsx'
require 'watir-webdriver'
require 'nokogiri'
require 'headless'

class NotLoadedYetError < StandardError;
end
class WrongCSSError < StandardError;
end

class Site < ActiveRecord::Base
  has_many :urls, dependent: :destroy
  has_many :rows, dependent: :destroy
  has_many :items, through: :urls
  has_and_belongs_to_many :groups
  has_many :logs, dependent: :destroy

  def get_urls_count(current_user)
    user_items = Item.joins(group: :user).where(groups: {user_id: current_user.id})
    (user_items & self.items).count
  end

  def check_for_violation
    urls = self.urls.where(violator: true)
    self.violator = urls.empty? ? false : true
    self.save
    p [self.name, 'violators - ', urls.size]
  end

  def get_violating_urls(current_user)
    Rails.cache.fetch([self, 'violators']) {
      #self.urls.where(violator: true).select("urls.urls, urls.price, groups.name, items.name").order('groups.name ASC, items.name ASC')
      #self.urls.where(violator: true)
      self.urls.joins(item: {group: :user}).where(violator: true, items: {group_id: current_user.groups.map(&:id)})

    }
  end

  def get_items
    Rails.cache.fetch([self, 'items']) { self.items }
  end

  def get_urls
    #Rails.cache.fetch([self, 'urls']) { self.urls }
    self.urls
  end

  def find_violating_urls(group)
    Rails.cache.fetch([self, group, 'urls']) do
      urls = site.urls.where(violator: true).find_all { |url| url.item.get_group_name == group.name }
      urls = urls.sort_by { |url| url.item.name }
    end
  end

  def self.get_row(site_id, group_id)
    row = Row.find_by(site_id: site_id, group_id: group_id)
    return row.html if row.present?

    urls = []
    site_urls = Url.where(site_id: site_id).to_a
    Item.where(group_id: group_id).order(:name).includes(:urls).each do |item|
      urls << (site_urls & item.urls.to_a).first
    end

    html = String.new
    urls.each do |url|
      if url.present?
        price = Site.spaces(url.price)
        css_class = !url.violator? ? 'muted' : 'text-error'
        html += "<td><a class=#{css_class} href=#{url.url} target=\"_blank\">#{price}</a></td>"
      else
        html += "<td>-</td>"
      end
    end
    row = Row.create(site_id: site_id, group_id: group_id, html: html)
    return row.html
  end

  def self.get_violators(current_user)
    ids = Url.joins(item: {group: :user}).where(violator: true).where(items: {group_id: current_user.groups.map(&:id)}).map(&:site_id).uniq
    Site.where(id: ids).includes(:urls).order(:name)
  end

  def update_cache
    self.touch
    self.get_items
    self.get_urls
    self.items.each do |item|
      item.get_standard_price
      item.get_standard_url
      item.get_group_name
      item.get_urls
    end
    self.groups.each do |group|
      group.touch
      self.rows.destroy_all
      Site.get_row(self.id, group.id)
    end
    logger.warn '------ cache is updated ------'
  end

###################### update price ###################
  def update_prices
    return if self.standard
    begin
      self.logs.destroy_all
      case self.method.to_i
        when 1
          result_array = self.parsing_site_method1
        when 2
          result_array = self.parsing_site_method2
        else
          logger.error 'error case metod'
          return
      end
      result_array = self.clear_result_array(result_array)
      raise WrongCSSError, "Wrong CSS? #{self.name}, item - #{self.css_item}, price - #{self.css_price}" if result_array.nil?
      self.update_urls(result_array)

      self.check_for_violation

      # rescue => e
      #   log_error :update_prices, e
      #   self.update_cache
      #   return
    end
    self.update_cache
    logger.warn '------ finished update_price ----- ' + self.name
  end

  def check_link(url, start_url) #исправление относительной ссылки
    begin
      #p "chek_link url = #{url}"
      site_name = start_url.scan(/(?:[-a-z_\d])+.(?:[-a-z])*(?:\.[a-z]{2,4})+/).first
      http_site_name = "http://" + site_name
      url_size = url[1..(url.size-1)].split('/').size
      #p "chek_link site_name = #{site_name}"

      if  url_size > 1 #проверка на редактируемого адреса
        add_str = http_site_name
      else
        add_str = start_url
      end

      if url.scan(site_name).first.nil? #проверка на относительную ссылку

        if url[0] != "/" && add_str[-1] != "/" #проверка на наличие первого слэша
          str = add_str + "/" + url
        else
          str = add_str + url
        end #проверка на наличие первого слэша

      else
        str = url
      end #проверка на относительную ссылку

      return str

    rescue => e
      log_error :check_link, e
      return nil
    end
  end

#исправление относительной ссылки

  def clear_result_array(result_array)
    begin
      if result_array.nil? || result_array.empty?
        return nil
      end
      r = Regexp.new(self.regexp)
      result_array.each do |item_array|
        item_array[0] = item_array[0].strip.gsub('Е', 'E').gsub('Н', 'H').gsub('О', 'O').gsub('Р', 'P').gsub('А', 'A').gsub('В', 'B').gsub('С', 'C').gsub('М', 'M').gsub('Т', 'T').gsub('К', 'K').gsub('Х', 'X').gsub('/', ' ').gsub('\\', ' ')

        if item_array[2].scan(/\d\.\d{3}/).count > 0
          item_array[2] = item_array[2].gsub('.', '') #костыль специально для kosilka.by
        end

        if item_array[2].scan(/\d\,\d{3}/).count > 0
          item_array[2] = item_array[2].gsub(',', '') #костыль специально для rodnoi.by
        end

        item_array[2] = item_array[2].strip.gsub(/\u00a0|\s/, '').gsub('\'', '').mb_chars.downcase.to_s[r]

        if item_array[2].nil?
          item_array[2] = 0
        else
          array = item_array[2].scan(r).sort_by { |elem| elem.to_f }
          case array.size
            when 1..2
              item_array[2] = array[0]
            when 3
              item_array[2] = array[1]
          end
        end
      end
      result_array = result_array.sort_by { |item_array| item_array[2].to_f }
      return result_array
    end
  rescue => e
    log_error :clear_result_array, e
  end

  def parsing_site_method1
    begin
      logger.warn "------ start parsing function method1 " + self.name + "------"
      if Rails.env.production?
        logger.warn 'Headless started'
        headless = Headless.new
        headless.start
      end
      css_page = self.css_pagination
      css_page = "no" if css_page.nil? || css_page.empty?
      css_item = self.css_item
      css_price = self.css_price
      timeout = 5

      result_array = []

      profile = Selenium::WebDriver::Firefox::Profile.new
      profile['permissions.default.image']=2
      browser = Watir::Browser.new :ff, :profile => profile

      self.search_url.split(/[,]+/).each do |site_url|
        browser.goto site_url
        begin #external exception
          begin #while
            begin # internal exception
              browser.element(:css => css_item).wait_until_present
              result_array += scrap_page(Nokogiri::HTML(browser.html, nil, 'utf-8'), css_item, css_price)
              if result_array.size != result_array.uniq.size
                result_array = result_array.uniq
                raise NotLoadedYetError, 'same page'
              end
              p browser.url
              p 'click'
              next_page_link = browser.element(:css => css_page).when_present(timeout).attribute_value('href')
              browser.element(:css => css_page).when_present(timeout).click
              browser.wait
            rescue Selenium::WebDriver::Error::StaleElementReferenceError => e
              p e.inspect
            rescue NotLoadedYetError => e
              p e.inspect
            end # internal exception

          end while next_page_link!=browser.url

        rescue Watir::Exception::UnknownObjectException => e
          p e.inspect
        rescue Watir::Wait::TimeoutError => e
          p 'done'
        end # external exception
      end

      result_array = result_array.uniq
      p result_array.size

      logger.warn "------done parsing function method1 " + self.name + "------"
      return result_array
    rescue => e
      log_error :parse_mehtod_one, e
    ensure
      browser.close
      if Rails.env.production?
        headless.destroy
        logger.warn 'Headless destroyed'
      end
    end
  end

  def parsing_site_method2 #функция парсинга сайта
    begin
      logger.warn "------ start parsing function " + self.name + "------"

      css_page = self.css_pagination
      css_page = "no" if css_page.nil? || css_page.empty? #присвоение хоть чего нибудь, если значение не передано

      start_page = "http://" + self.name
      referer = start_page
      result_array = []
      site_urls_array = self.search_url.split(/[,]+/)

      site_urls_array.each do |site_url|
        begin
          url_site_start = site_url
          previous_page = open(site_url, "Referer" => referer)
          cookies = previous_page.meta["set-cookie"] || ""
          cookies = "" if start_page == "http://technostil.by" #затычка для technostil.by

          begin
            last_page = site_url

            begin
              page = open(site_url, "Cookie" => cookies, "Referer" => referer)
            rescue => e
              page = open(URI.escape(site_url), "Cookie" => cookies, "Referer" => referer)
            end

            page = page.set_encoding 'utf-8'
            html = Nokogiri::HTML(page.read, nil, 'utf-8')
            name_array = html.css(self.css_item)
            price_array = html.css(self.css_price)

            if name_array.size != price_array.size #проверка соответствия кол-ва товаров и цен
              logger.error "amount name:  #{name_array.size.to_s}, #{self.css_item}"
              logger.error "amount price:  #{price_array.size.to_s}, #{self.css_price}"
              next
            end #проверка соответствия кол-ва товаров и цен

app/controllers/sites_controller.rb
require 'zip/zip'
require 'rubyXL'
require 'axlsx'

class SitesController < ApplicationController
  before_filter :authenticate_user!
  before_action :set_site, only: [:show, :edit, :update, :destroy, :logs, :logs_submit, :violators, :update_prices]

  def row
    render text: Site.get_row(params[:id], params[:group])
  end

  def violators
    @violating_urls = @site.get_violating_urls(current_user).includes(item: :group).order('groups.name ASC, items.name ASC')
    render action: "violators", layout: nil
  end

  def logs
    @logs = @site.logs.order(:message)
    @names = Item.all.order(:name).pluck(:id, :name)
  end

  def search
    @items = []
    @item_sort = []
    items = []

    if params[:item_search].present?
      params[:direction] = %w[asc desc].include?(params[:direction]) ? params[:direction] : 'asc'

      queries = params[:item_search].upcase.gsub(/\s*,\s*/, ',')
      queries.split(',').each do |query|
        items += Item.item_search(query)
      end
      items.compact!
      @items = items.select { |item| item.group.user == current_user }
      redirect_to :back, alert: "#{params[:item_search]} не найден" and return if @items.empty?
      params[:sort] = @items.map(&:name).include?(params[:sort]) ? params[:sort] : @items.first.name
      @item_sort = Item.find_by(name: params[:sort]) || @items.first

    end

  end

  def update_prices
    if Rails.env.production?
      @site.delay(run_at: 10.seconds.from_now).update_prices
    else
      @site.update_prices
    end
    #LogMailer.update_report(current_site).deliver
    flash[:notice] = "Цены обновляются. Обычно это занимает 1-2 минуты для каждого сайта. Обновите страницу позже."

    redirect_to site_path(@site)
  end

  def logs_submit
    @site.logs.each do |log|
      url = Url.find_by_url(log.message.split(", ")[1].gsub("\"", ""))
      if url.nil?
        item = Item.find_by_name(log.name_found)
        next if item.nil?

        url = @site.update_url(log.price_found, log.message.split(", ")[1].gsub("\"", ""), item)
      else
        item = Item.find_by_name(log.name_found)
        next if item.nil?

        next if item.name == log.name_found

        url.item = item
        url.locked = true
        url.save
      end
    end
    redirect_to site_path(@site)
  end

  def index
    @sites = current_user.admin? ? Site.all.order(:name) : Site.joins(:groups).where(groups: {'user' => current_user}).uniq.order(:name)
  end

  def show
    @urls = @site.urls.joins(item: {group: :user}).where(items: {group_id: current_user.groups.map(&:id)}).order('groups.name ASC, items.name ASC')
  end

  def new
    @site = Site.new
  end

  def edit
  end

  def create
    @site = Site.new(site_params)

    respond_to do |format|
      if @site.save
        format.html { redirect_to @site, notice: 'Site was successfully created.' }
        format.json { render action: 'show', status: :created, location: @site }
      else
        format.html { render action: 'new' }
        format.json { render json: @site.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @site.update(site_params)
        format.html { redirect_to @site, notice: 'Сайт успешно обновлен.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @site.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @site.destroy
    respond_to do |format|
      format.html { redirect_to sites_url }
      format.json { head :no_content }
    end
  end

  def stop_list
    @sites = Site.get_violators(current_user).paginate(:page => params[:page], :per_page => 10)
  end

  private
# Use callbacks to share common setup or constraints between actions.
  def set_site
    @site = current_user.admin? ? Site.find(params[:id]) : Site.joins(:groups).where(id: params[:id], groups: {'user' => current_user}).readonly(false).uniq.first
    redirect_to root_path if @site.nil?
  end

# Never trust parameters from the scary internet, only allow the white list through.
  def site_params
    params.require(:site).permit! #(:name, :regexp, :standard, :company_name, :out_of_ban_time, :email, urls: :url, :items)
  end

end

app/helpers/sites_helper.rb
module SitesHelper
end

app/views/sites/_form.html.erb
<%= form_for @site, :html => {:class => 'form-horizontal'} do |f| %>
    <div class="control-group">
      <%= f.label :name, :class => 'control-label' %>
      <div class="controls">
        <%= f.text_field :name, :class => 'span10' %>
      </div>
    </div>
    <div class="control-group">
      <%= f.label :company_name, :class => 'control-label' %>
      <div class="controls">
        <%= f.text_field :company_name, :class => 'span10' %>
      </div>
    </div>
    <div class="control-group">
      <%= f.label :email, :class => 'control-label' %>
      <div class="controls">
        <%= f.text_field :email, :class => 'span10' %>
      </div>
    </div>
    <% if current_user.admin? %>
        <div class="control-group">
          <%= f.label :css_item, :class => 'control-label' %>
          <div class="controls">
            <%= f.text_field :css_item, :class => 'span10' %>
          </div>
        </div>
        <div class="control-group">
          <%= f.label :css_price, :class => 'control-label' %>
          <div class="controls">
            <%= f.text_field :css_price, :class => 'span10' %>
          </div>
        </div>
        <div class="control-group">
          <%= f.label :css_pagination, :class => 'control-label' %>
          <div class="controls">
            <%= f.text_field :css_pagination, :class => 'span10' %>
          </div>
        </div>
        <div class="control-group">
          <%= f.label :regexp, :class => 'control-label' %>
          <div class="controls">
            <%= f.text_field :regexp, :class => 'span10' %>
          </div>
        </div>
        <div class="control-group">
          <%= f.label :method, :class => 'control-label' %>
          <div class="controls">
            <%= f.text_field :method, :class => 'span10' %>
          </div>
        </div>
        <div class="control-group">
          <%= f.label :search_url, :class => 'control-label' %>
          <div class="controls">
            <!--<textarea rows="5">-->
            <%= f.text_area :search_url, rows:10, cols: 40, :class => 'span10' %>
            <!--</textarea>-->
          </div>
        </div>
        <div class="control-group">
          <%= f.label :standard, :class => 'control-label' %>
          <div class="controls">
            <%= f.check_box :standard, :class => 'check_box' %>
          </div>
        </div>
    <% end %>

    <div class="form-actions">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t('helpers.links.cancel')),
                  sites_path, :class => 'btn' %>
    </div>
<% end %>

app/views/sites/edit.html.erb
<%- model_class = Site -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/sites/export_preview.html.erb
<div class="page-header">
  <h2><%= current_user.username %></h2>
</div>

<% if current_user.admin? %>
    <div class="row">
      <div class="span1 offset1">
        /<%= @sites[0] %>
      </div>
    </div>
    <div class="row">
      <div class="span12 offset2">
        <table>
          <thead>
          <strong>/all_sites.xlsx</strong>
          <% Site.first.attributes.keys[1..3].each do |key| %>
              <th><%= key %></th>
          <% end %>
          </thead>
          <tbody>
          <% @sites[1].each do |site| %>
              <tr>
                <% site.attributes.values[1..3].each do |value| %>
                    <td><%= value %></td>
                <% end %>
              </tr>
          <% end %>
          </tbody>
        </table>
      </div>
    </div>


    <% @folders.each do |user_folder| %>
        <div class="row">
          <div class="span1 offset1">
            /<%= user_folder[0] %>
          </div>
        </div>
        <% user_folder[1].each do |folder| %>
            <div class="row">
              <div class="span1 offset2">
                /<%= folder[0] %>
              </div>
            </div>
            <div class="row">
              <div class="span2 offset3">
                <table>
                  <thead>
                  <th>/items.xlsx</th>
                  </thead>
                  <tbody>
                  <% folder[1].each do |item| %>
                      <tr>
                        <td>
                          <%= item.name %>
                        </td>
                      </tr>
                  <% end %>
                  </tbody>

                </table>
              </div>
              <div class="span2 offset1">
                <table>
                  <thead>
                  <th>/sites.xlsx</th>
                  </thead>
                  <tbody>
                  <% folder[2].each do |site| %>
                      <tr>
                        <td>
                          <%= site.name %>
                        </td>
                      </tr>
                  <% end %>
                  </tbody>

                </table>
              </div>
              <div class="span1">
                <strong>/<%= folder[3] %></strong>
              </div>
            </div>

        <% end %>
    <% end %>

    <%= link_to 'Экспорт', export_sites_path, :class => 'btn btn-primary' %>

<% end %>

app/views/sites/import_preview.html.erb
<%- model_class = Site -%>
<div class="page-header">
  <h2><%= current_user.username %></h2>
</div>

<table class="table table-striped">
  <thead>
  <th>Группа</th>
  <th>Название</th>
  <th>Цена</th>
  </thead>
  <tbody>
  <% @items.each do |item| %>
      <tr>
        <td><%= item[0] %></td>
        <td><%= item[1] %></td>
        <td><%= spaces(item[2]) %></td>
      </tr>
  <% end %>
  </tbody>
</table>

<%= link_to 'Импорт', new_site_path, :class => 'btn btn-primary' %>
<%= link_to 'Назад', settings_path, :class => 'btn' %>

app/views/sites/index.html.erb
<%#= ENV.to_hash %>

<%- model_class = Site -%>
<div class="page-header">
  <h2><%= t '.title', :default => model_class.model_name.human.pluralize.titleize %></h2>
</div>

<table class="table table-striped">
  <thead>
  <tr>
    <th><%= model_class.human_attribute_name(:name) %></th>
    <th><%= model_class.human_attribute_name(:group) %></th>
    <th><%= model_class.human_attribute_name(:company_name) %></th>
    <th><%= t '.actions', :default => t('helpers.actions') %></th>
  </tr>
  </thead>
  <tbody>
  <% @sites.order(:name).includes(:groups).each do |site| %>
      <tr <%= (site.violator?) ? " class=\"error\"".html_safe : '' %>"" >
      <td><%= link_to site.name, site_path(site), class: 'tdfade' %></td>
      <td>
        <%- groups = current_user.admin? ? site.groups : site.groups & current_user.groups %>
        <% groups.each do |group| %>
            <%= group.name %>
        <% end %></td>
      <td><%= site.company_name %></td>


      <td>
        <% if current_user.admin? %>
            <%= link_to t('.edit', :default => t('helpers.links.edit')),
                        edit_site_path(site), :class => 'btn btn-mini' %>


            <%= link_to t('.destroy', :default => t('helpers.links.destroy')),
                        site_path(site),
                        :method => :delete,
                        :data => {:confirm => t('.confirm', :default => t('helpers.links.confirm', :default => 'Are you sure?'))},
                        :class => 'btn btn-mini btn-danger' %>
        <% end %>
        <% unless site.standard? %>
            <%= link_to 'Обновить цены', update_prices_site_path(site) ,class: 'btn btn-mini' %>
        <% end %>
      </td>
      </tr>
  <% end %>
  </tbody>
</table>
<% if current_user.admin? %>
    <%= link_to t('.new', :default => t('helpers.links.new')),
                new_site_path,
                :class => 'btn btn-primary' %>
<% end %>

app/views/sites/logs.html.erb
<div class="page-header">
  <h1><%= @site.name %></h1>

</div>
<table class="table table-striped">
  <thead>
  <tr>
    <th>Тип</th>
    <th>Сообщение</th>
    <th>Позиция</th>
    <th>Цена</th>
  </tr>
  </thead>
  <tbody>
  <% @logs.each do |log| %>
      <tr>
        <td><%= log.log_type %></td>
        <% if !log.message.nil? %>
            <%- message = log.message.gsub(/[\[\]\"]/, "").split(', ') %>
            <td><%= link_to message[0], message[1], target: "_blank" %></td>
        <% else %>
            <td></td>
        <% end %>
        <td width="350px">
          <%= best_in_place log, :name_found, :type => :input, :classes => 'typeahead',
                            :html_attrs => {:'data-provide' => 'typeahead',
                                            :'data-source' => log.names(current_user),
                                            :'autocomplete' => 'off'} %>

        </td>
        <td><%= spaces(log.price_found) %></td>

      </tr>
  <% end %>
  </tbody>
</table>

<div class="form-actions">
  <%= link_to t('.back', :default => t('helpers.links.back')),
              site_path(@site), :class => 'btn' %>
  <%= link_to 'Изменить позиции', logs_submit_site_path(@site), :class => 'btn' %>

</div>

<br><br><br>
Поисковые ссылки:
<br>
<% if !@site.search_url.nil? %>
    <p>
      <% @site.search_url.split(',').each do |search_url| %>
        <p><%= link_to search_url, search_url %></p>
    <% end %>
    </p>
<% end %>

app/views/sites/new.html.erb
<%- model_class = Site -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/sites/show.html.erb
<%- model_class = Site -%>
<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @site.name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:company_name) %>:</strong></dt>
  <dd> <%= @site.company_name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:email) %>:</strong></dt>
  <dd> <%= @site.email %></dd>
</dl>

<table class="table table-condensed">
  <th>Производитель</th>
  <th>Позиция</th>
  <th class="num">Цена сайта</th>
  <th class="num">Эталон</th>
  <th class="num">Разница, руб.</th>
  <th class="num">Разница, %</th>

  <% @urls.each do |url| %>
      <%= cache(url) do %>
          <tr class=<%= url.violator? ? 'error' : '' %>>
            <td><%= url.item.group.name %></td>
            <td><%= url.item.name %></td>
            <% if url.price > 0 %>
                <td class="num"> <%= link_to spaces(url.price), url.url %></td>
            <% else %>
                <td class="num"> <%= link_to 'n/a', url.url %></td>
            <% end %>
            <%- standard_price = url.item.get_standard_price %>
            <td class="num"><%= spaces(standard_price) %></td>
            <% if url.price > 0 && standard_price > 0 %>
                <td class="num"><%= spaces(standard_price - url.price) %></td>
                <td class="num"><%= '%.1f' % ((standard_price/url.price - 1)*100) %>
                %
                </td>
            <% else %>
                <td></td>
                <td></td>
            <% end %>
          </tr>
      <% end %>
  <% end %>
</table>

<div class="form-actions">
  <%= link_to 'Весь список',
              stop_list_sites_path, :class => 'btn' %>
  <%= link_to t('.update_prices', :default => t('helpers.links.update_prices')),
              update_prices_site_path(@site), :class => 'btn' %>
  <% if current_user.admin? %>
      <%= link_to 'Лог', logs_site_path(@site), :class => 'btn' %>
  <% end %>
</div>

app/views/sites/stop_list.html.erb
<h3>Стоп лист</h3>

<div class="accordion" id="accordion_site">

  <% @sites.each do |site| %>
      <div class="accordion-heading">
        <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion_site" href=<%= '#collapse' + site.id.to_s %>>
          <table class="table ">
            <th class="span3 btn"><%= site.name %></th>
            <th class="span3 btn"> <%= site.company_name %></th>
            <th class="span2 btn">Товаров -
              <%= site.get_urls_count(current_user) %></th>
            <th class="span2 btn site<%= site.id.to_s %>"></th>
          </table>
        </a>

      </div>
      <div class="accordion-body collapse" id=<%= 'collapse' + site.id.to_s %>>
        <div class="accordion-inner">
          <%= cache(site) do %>
              <table class="table table-striped">
                <thead>
                <tr>
                  <th>Бренд</th>
                  <th>Позиция</th>
                  <th class="num">Цена сайта</th>
                  <th class="num">Эталон</th>
                  <th class="num">Разница, руб.</th>
                  <th class="num">Разница, %</th>
                </tr>
                </thead>
                <tbody id=<%= 'tbody' + site.id.to_s %>>
                </tbody>
              </table>
              <%= javascript_tag do %>
                  $.ajax({
                  type: "GET",
                  cache: false,
                  url: "<%= violators_site_path(site) %>",
                  dataType: "html"
                  })
                  .success(function( data ) {
                  $( "#tbody<%= site.id %>" ).html( data );

                  });
              <% end %>
          <% end %>
        </div>
      </div>
  <% end %>

</div>

<div class="paginate pagination-centered">
  <%= will_paginate @sites %>
</div>