config/routes.rb
Distibutor::Application.routes.draw do
  mount Tail::Engine, at: '/tail'

  get 'main/index'
  get 'main/main'

  resources :logs, only: [:index, :destroy] do
    collection do
      get 'clear_log' => 'logs#clear_log'
    end
  end

  resources :settings, only: [:index, :show, :edit, :update] do
    collection do
      post 'import_preview' => 'settings#import_standard_prices_preview'
      get 'import_standard_prices' => 'settings#import_standard_prices'

      post 'all' => 'settings#all_sites_preview'
      get 'all' => 'settings#all_sites_import'

      post 'import_shops_preview' => 'settings#import_user_sites_preview'
      get 'import_shops' => 'settings#import_user_sites'

      get 'export_shops_preview' => 'settings#export_shops_preview'
      get 'export_shops' => 'settings#export_shops'
    end
  end

  resources :items, only: [:index, :show] do
    collection do
      get 'refine_items' => 'items#refine_items'
    end
  end

  resources :urls, only: [:index] do
    member do
      get 'upd' => 'urls#update_single_price'
    end
    collection do
      get 'update_violators' => 'urls#update_violators'
      get 'find_urls' => 'urls#find_urls'
    end
  end

  resources :sites, only: [:index, :show, :edit, :update, :new] do
    collection do
      get 'stop_list' => 'sites#stop_list'
      get 'search' => 'sites#search'
    end

    member do
      get 'logs'
      get 'logs_submit'
      get 'violators'
      get 'row'
      get 'update_prices' => 'sites#update_prices'
    end

  end

  get '/dj' => DelayedJobWeb, :anchor => false

  resources :groups, only: [:show]

  devise_for :users

  root 'main#index'

end

app/views/layouts/_google.html.erb
<script>
    (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
        (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
            m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
    })(window,document,'script','//www.google-analytics.com/analytics.js','ga');
    ga('create', 'UA-53378414-1', 'auto');
    ga('send', 'pageview');
</script>

app/views/layouts/_yandex.html.erb
<!-- Yandex.Metrika counter -->
<script type="text/javascript">
    (function (d, w, c) {
        (w[c] = w[c] || []).push(function() {
            try {
                w.yaCounter25440242 = new Ya.Metrika({id:25440242,
                    webvisor:true,
                    clickmap:true,
                    trackLinks:true,
                    accurateTrackBounce:true});
            } catch(e) { }
        });

        var n = d.getElementsByTagName("script")[0],
                s = d.createElement("script"),
                f = function () { n.parentNode.insertBefore(s, n); };
        s.type = "text/javascript";
        s.async = true;
        s.src = (d.location.protocol == "https:" ? "https:" : "http:") + "//mc.yandex.ru/metrika/watch.js";

        if (w.opera == "[object Opera]") {
            d.addEventListener("DOMContentLoaded", f, false);
        } else { f(); }
    })(document, window, "yandex_metrika_callbacks");
</script>
<noscript><div><img src="//mc.yandex.ru/watch/25440242" style="position:absolute; left:-9999px;" alt="" /></div></noscript>
<!-- /Yandex.Metrika counter -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>B2B Soft</title>
  <!--[if lt IE 9]>
  <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
  <![endif]-->
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0 user-scalable=yes">
</head>
<body>

<div class="navbar navbar-inverse navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container-fluid">
      <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </a>


      <div class="nav-collapse">
        <ul class="nav">
          <li><%= link_to 'B2B Soft', root_path, class: 'brand' %></li>
          <% if user_signed_in? %>
              <li class="divider-vertical"></li>
              <%- groups = current_user.admin? ? Group.all.order(:name) : current_user.groups.order(:name) %>
              <% groups.each do |group| %>
                  <%- class_name = 'group' %>
                  <% if current_page?(controller: 'groups', action: 'show', id: group.id) %>
                      <%- class_name = class_name + ' active' %>
                  <% end %>
                  <li class=<%= class_name %>><%= link_to group.name, group_path(group) %></li>

              <% end %>
              <li class="divider-vertical"></li>
              <li class=<%= 'active' if current_page?(controller: 'sites', action: 'stop_list') %>><%= link_to (t 'nav.stoplist'), stop_list_sites_path %></li>
              <li class=<%= 'active' if current_page?(controller: 'sites', action: 'index') %>><%= link_to (t 'nav.sites'), sites_path %></li>
              <li class="divider-vertical"></li>
              <%= form_tag search_sites_path, method: :get, class: 'navbar-form pull-left' do %>
                  <div class="input-prepend">
                    <span class="add-on"><i class="icon-search"></i></span>
                    <%= search_field_tag 'item_search', nil, class: 'span3', placeholder: 'пример: MTD 46 PB, K 2.300' %>
                    <%= submit_tag 'Искать', :class => 'btn btn-inverse' %>
                  </div>
              <% end %>
              <li class="divider-vertical"></li>
          <% else %>

          <% end %>

        </ul>

        <ul class="nav pull-right">
          <% if user_signed_in? %>
              <li class=<%= 'active' if current_page?(controller: 'settings', action: 'index') %>><%= link_to (t 'nav.settings'), settings_path %></li>
              <li><%= link_to((t('nav.logout')), destroy_user_session_path, :method => :delete) %></li>
          <% else %>

              <li><a class="brand no_spin" href="#">Позвоните нам +375 29 650 24 98 или</a></li>
              <li><a class="brand no_spin" style="color: #0077aa" href="mailto:sales@b2bsoft.by">напишите</a></li>
              <li class="divider-vertical"></li>
              <li><a href=""></a></li>
              <li><%= link_to(t('nav.login'), new_user_session_path, class: 'brand no_spin') %></li>

          <% end %>
        </ul>

      </div>
    </div>
  </div>
</div>



<%= image_tag 'indicator.gif', class: 'spin', hidden: true, style: 'margin: 20px' %>



<div class="container-fluid">
  <div class="row-fluid">

    <% flash.each do |name, msg| %>
        <div class="alert alert-<%= name == :notice ? 'success' : 'error' %>">
          <button type="button" class="close"
                  data-dismiss="alert">&times;</button> <%= msg %> </div>

    <% end %>



    <%= yield %>

  </div>
</div>
<%- if Rails.env.production? %>
    <%= render partial: 'layouts/yandex' %>
    <%= render partial: 'layouts/google' %>
<% end %>
</body>
</html>